# .github/workflows/main-approval-deploy.yml


on:
  pull_request:
    branches:
      - main   # ✅ enforce approval for PRs into main
  push:
    branches:
      - main   # ✅ deploy after merge to main

jobs:
  approval-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: main-protection   # 👈 requires environment approval
    steps:
      - name: Enforce Approval
        run: echo "✅ Approval enforced via environment reviewers"



     
